export const CLIENTS =[
    {
        id: 1,
        title: 'Feneuil Pointillart',
        latitude: 49.1738,
        longitude: 3.9561,
        numberOfBoxes: 10,
        problem: true,
    },
        {
        id: 2,
        title: 'Mumm',
        latitude: 49.2635,
        longitude: 4.037,
        numberOfBoxes: 43,
        problem: false,
    },
    {
        id: 3,
        title: 'Veuve Clicquot Ponsardin ',
        latitude: 49.2596,
        longitude: 4.0336,
        numberOfBoxes: 247,
        problem: false,
    },
    {
        id: 4,
        title: 'Papa et Alec :)',
        latitude: 49.2527,
        longitude: 4.0317,
        numberOfBoxes: 100,
        problem: false,
    },
    {
        id: 5,
        title: 'Taittinger',
        latitude: 49.2624,
        longitude: 4.0346,
        numberOfBoxes: 0,
        problem: false,
    },
    {
        id: 6,
        title: 'Le PEtite Cantoche',
        latitude: 49.2556,
        longitude: 4.0310,
        numberOfBoxes: 0,
        problem: false,
    },
]
